export const UI = `
<canvas id="arena" aria-label="Three-dimensional orbital arena"></canvas><div class="vignette"></div>
<output id="fps-counter" aria-label="Frames per second" aria-live="off">— FPS</output>
<header id="header"><a id="home-brand" class="brand" href="/" aria-label="Neon Breach"><span class="brand-mark">N<span>↗</span></span><span>NEON<span class="brand-light">BREACH</span><small>ORBITAL CONTRACT SYSTEM</small></span></a><div class="station"><span class="live-dot"></span><span id="nav-location">LANDING / YEAR 2191</span></div><button class="icon-button" id="settings-open">Settings</button></header>
<main id="landing" class="screen landing">
 <section class="hero"><div class="eyebrow"><span class="mini-line"></span> EARTH IS SILENT. THE ARENA ISN’T.</div><h1>NEON<br><span>BREACH</span></h1><p class="tagline">The contract ends when the signal dies.</p><p class="intro">Four operators. One failing station.<br>Get in. Stay moving. Leave a signal.</p><div class="specs"><div><b>01—04</b><span>SOLO / ONLINE</span></div><div><b>180<span>s</span></b><span>PER CONTRACT</span></div><div><b>10</b><span>TO TAKE IT ALL</span></div></div></section>
 <section class="terminal"><div class="panel-top"><span id="entry-location">01 / ESTABLISH UPLINK</span><span class="terminal-dots">▰ ▰ ▰</span></div><h2 id="entry-title">Your contract<br>starts here.</h2><p class="subtle" id="entry-note">Bring friends, or take on 3 bots. No account.</p>
 <form id="room-form"><label for="callsign">OPERATOR CALLSIGN <span>2–10 CHARACTERS</span></label><input id="callsign" name="callsign" placeholder="E.G. VEX" minlength="2" maxlength="10" pattern="[A-Za-z0-9]{2,10}" autocomplete="off" autocapitalize="characters" spellcheck="false" required>
 <div id="create-options"><button class="primary" id="create" type="submit">Create Room <span>↗</span></button><button class="secondary solo-button" id="solo" type="button">Play Solo <span>→</span></button><p class="solo-hint">You + 3 labeled bots. Same combat rules.</p><button id="join-open" class="secondary" type="button">Join Room <span>→</span></button></div>
 <section id="join-panel" hidden><label for="room-code">ROOM CODE <span>FROM YOUR HOST</span></label><input id="room-code" placeholder="ROOM CODE" maxlength="6" autocomplete="off" autocapitalize="characters" spellcheck="false"><button id="join" class="primary" type="button">Join Room <span>→</span></button><button id="join-back" class="text-button" type="button">Back</button></section></form>
 <div class="panel-foot"><span class="live-dot"></span><span id="landing-connection">CONNECTING TO STATION…</span><span>FFA / 1 ARENA</span></div></section>
 <div class="landing-bottom"><span class="sector">SECTOR 07 <i>+</i> THE SHATTERED RELAY</span><button class="text-button" id="how-open">How to Play <span>↓</span></button><span class="dim">NO DOWNLOAD. NO SECOND TEAM.</span></div>
 <section class="briefing" id="landing-rules"><div><span class="eyebrow">KNOW THE CONTRACT</span><h2>One rifle.<br>Every operator for themselves.</h2><p class="subtle">Move, aim, and make three hits count.<br>Every eliminated operator returns.</p></div><ol id="rules-list"></ol></section>
</main>
<main id="lobby" class="screen lobby" hidden>
 <section class="lobby-intro"><div class="eyebrow" id="lobby-mode">UPLINK ESTABLISHED / PRIVATE ROOM</div><h1><span class="title-white" id="lobby-title">ASSEMBLE</span><br><span id="lobby-subtitle">THE SIGNAL.</span></h1><p class="tagline" id="lobby-tagline">Send the code. Settle the contract.</p><div class="code-panel"><span id="code-label">ROOM CODE</span><div><strong id="lobby-code" tabindex="0"></strong><button id="copy-code" class="icon-button">Copy Code</button></div><small id="lobby-invite">Open this game on another device and enter the code.</small><small id="copy-status" role="status"></small></div><div class="lobby-meta"><span>FREE-FOR-ALL</span><span>3 MINUTES</span><span>FIRST TO 10</span></div></section>
 <section class="terminal roster-panel"><div class="panel-top"><span>02 / OPERATOR MANIFEST</span><span id="player-count"></span></div><h2 id="lobby-heading">Awaiting deployment.</h2><div id="roster"></div><p id="host-note" class="subtle"></p><button class="primary" id="start">Start Match <span>↗</span></button><button class="primary" id="lobby-replay" hidden>Play Again</button><button class="secondary" id="lobby-how-open">How to Play</button><button class="warning-button" id="leave-lobby">Leave Room</button><p class="nav-consequence">Leave Room removes only your seat; the other operators stay connected.</p></section>
 <details class="lobby-briefing" open><summary>CONTRACT RULES & CONTROLS</summary><ol id="lobby-rules"></ol></details>
</main>
<section id="hud" hidden aria-label="Match heads-up display"><div class="hud-top"><div class="match-label"><b>NEON BREACH</b><span id="match-code"></span><button id="match-settings" class="menu-button">Menu <span>Esc</span></button></div><div class="clock"><span>CONTRACT REMAINING</span><strong id="timer">03:00</strong><small>FIRST TO 10</small></div><div class="score-panel"><div class="score-head">OPERATORS <span>ELIMS</span></div><div id="scores"></div></div></div><div id="feed" aria-live="polite"></div><div id="crosshair"><i></i><i></i><i></i><i></i></div><div id="hitmarker">╳</div><div id="damage-direction">▲</div><div id="damage-flash"></div><div class="cell-status" id="cell-status"></div><div class="health-block" id="health-block"><span>VITAL SYSTEMS</span><div><strong id="hp">100</strong><small>/ 100</small><b id="life-status">ONLINE</b></div><div class="health-track"><i id="hp-bar"></i></div><div class="dash-track"><span>SHIFT / DASH</span><i><b id="dash-bar"></b></i><strong id="dash-status">READY</strong></div></div><div class="weapon-info"><span>PULSE RIFLE / 01</span><strong>∞ <small>ENERGY</small></strong><span>34 DMG <i>·</i> HITSCAN</span></div><div class="bottom-status"><span id="connection">● CONNECTED</span><span id="latency">— MS</span></div><div id="touch-controls"><div id="aim-zone" aria-label="Drag to aim"></div><div id="stick" aria-label="Movement joystick"><span id="stick-thumb"></span><small>MOVE</small></div><button id="dash-touch" aria-label="Dash">↟<small>DASH</small></button><button id="fire" aria-label="Fire rifle">◎<small>FIRE</small></button></div><div class="center-overlay" id="respawn" hidden><span class="eyebrow">SIGNAL INTERRUPTED</span><h2>OPERATOR DOWN</h2><p>Reconstructing in <strong id="respawn-timer">5</strong></p></div><div class="center-overlay resume" id="resume" hidden><span class="eyebrow">CONTRACT IN PROGRESS</span><h2>RE-ENTER THE SIGNAL.</h2><p>Your cursor is released; the match is live.</p><button id="resume-button" class="primary">Click to Resume <span>↗</span></button><small>WASD MOVE · MOUSE AIM · CLICK FIRE · SHIFT DASH</small></div></section>
<main id="results" class="screen results" hidden><div class="result-card"><span class="eyebrow" id="result-mode">CONTRACT CLOSED / SIGNAL SURVIVES</span><div class="result-emblem">⌁</div><p id="result-label">LAST SIGNAL STANDING</p><h1 id="winner"></h1><p id="win-reason" class="subtle"></p><div id="final-scores"></div><button id="replay" class="primary">Play Again <span>↗</span></button><p class="subtle" id="replay-note"></p><button id="results-lobby" class="secondary">Return to Lobby</button><button id="results-settings" class="secondary">Settings</button><button id="leave-results" class="warning-button">Leave Room</button></div></main>
<button id="audio-enable" class="audio-enable" type="button">ENABLE AUDIO <span>↗</span></button>
<dialog id="pause-menu" class="visor-panel" aria-labelledby="pause-title"><div class="panel-top"><span>03 / LOCAL MENU</span><span id="pause-live">MATCH STILL LIVE</span></div><h2 id="pause-title">Hold your signal.</h2><p id="pause-note" class="subtle">Only your controls are paused; the clock, incoming damage and other operators continue.</p><p id="pause-life" class="pause-life" role="status"></p><button id="pause-resume" class="primary">Resume <span>↗</span></button><button id="pause-settings" class="secondary">Settings</button><button id="pause-lobby" class="warning-button">Return to Lobby</button><button id="leave-match" class="warning-button">Quit Match</button><p class="nav-consequence">Return to Lobby keeps your room seat. Quit Match removes it. The server applies the normal last-player rule.</p></dialog>
<dialog id="settings" class="visor-panel" aria-labelledby="settings-title"><div class="panel-top"><span id="settings-location">OPERATOR SETTINGS</span><button id="settings-back-top" class="text-button">Back</button></div><h2 id="settings-title">Tune your visor.</h2><label for="sensitivity">AIM SENSITIVITY <output id="sensitivity-value"></output></label><input id="sensitivity" type="range" min="0.25" max="2.5" step="0.05"><fieldset class="audio-settings"><legend>STATION AUDIO</legend><div class="audio-levels">${(['master', 'music', 'effects', 'ambience', 'ui'] as const).map(bus => `<div><label for="audio-${bus}">${bus === 'ui' ? 'UI' : bus.toUpperCase()}<output id="audio-${bus}-value"></output></label><input id="audio-${bus}" type="range" min="0" max="100" step="1"></div>`).join('')}</div><label class="toggle"><span>MUTE ALL SOUND</span><input type="checkbox" id="audio-mute"></label><p id="audio-status" class="subtle" role="status"></p></fieldset><label class="toggle"><span>TOUCH CONTROLS</span><input type="checkbox" id="touch-enabled"></label><p class="nav-consequence">Changes apply immediately and save on this device. Your room and match stay connected.</p><button id="settings-back" class="primary">Back <span>↗</span></button></dialog>
<dialog id="how-menu" class="visor-panel" aria-labelledby="how-title"><div class="panel-top"><span id="how-location">OPERATOR BRIEFING</span><button id="how-back-top" class="text-button">Back</button></div><h2 id="how-title">Know the contract.</h2><ol id="how-rules"></ol><p class="subtle">Esc / Menu opens your local menu; it never pauses the shared match.</p><button id="how-back" class="primary">Back <span>↗</span></button></dialog>
<dialog id="confirm-menu" class="visor-panel" aria-labelledby="confirm-title"><div class="panel-top"><span id="confirm-location">CONFIRM NAVIGATION</span></div><h2 id="confirm-title">Leave the signal?</h2><p id="confirm-message"></p><p id="confirm-effect" class="subtle"></p><p id="confirm-progress" role="status"></p><div class="confirm-actions"><button id="confirm-cancel" class="secondary" autofocus>Cancel</button><button id="confirm-accept" class="primary confirm-destructive">Leave Room</button></div><button id="confirm-reconnect" class="secondary" hidden>Reconnect</button><button id="confirm-home" class="warning-button" hidden>Return to Landing</button></dialog>
<dialog id="connection-overlay" class="visor-panel" aria-labelledby="connection-title"><span class="eyebrow">UPLINK INTERRUPTED</span><h2 id="connection-title">Connection lost.</h2><p id="connection-message">Connection lost; your match continues on the server.</p><button id="connection-reconnect" class="primary">Reconnect</button><button id="connection-home" class="warning-button">Return to Landing</button><p class="nav-consequence">Disconnected operators leave the match under the server’s normal rules.</p></dialog>
<div id="toast" role="status" hidden></div>`;
