import assert from 'node:assert/strict';
import { chromium, type Page } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { realtimeFixture } from './realtime-fixture';
import type { Snapshot } from '../shared/protocol';
import { validPosition } from '../shared/world';

const server = await realtimeFixture(), checks: string[] = [], errors: string[] = [], matches: unknown[] = [];
const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));
async function until(fn: () => boolean | Promise<boolean>, message: string, timeout = 8000) { const at = performance.now(); while (!await fn()) { if (performance.now() - at > timeout) throw new Error(message); await sleep(40); } }
const browser = await chromium.launch({ headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--use-angle=metal', '--disable-background-timer-throttling', '--disable-renderer-backgrounding'] });
let code = '', idA = '', idB = '';
const state = () => server.rooms.rooms.get(code)!, player = (id: string) => state().players.get(id)!;
const pass = (message: string) => { checks.push(message); console.log(`PASS ${message}`); };
const contexts = await Promise.all([browser.newContext({ viewport: { width: 1280, height: 800 } }), browser.newContext({ viewport: { width: 1280, height: 800 } })]);
for (const context of contexts) await context.addInitScript({ content: `sessionStorage.setItem('nb-intro-seen-v1','1'); localStorage.setItem('nb-audio',JSON.stringify({master:0,music:0,muted:true})); window.__name=v=>v; window.__dropDash=false; const send=WebSocket.prototype.send; WebSocket.prototype.send=function(data){ window.__gameSocket=this; if(window.__dropDash && typeof data==='string' && data.startsWith('42[')){try{const [event,input]=JSON.parse(data.slice(2));if(event==='input'&&input.dash){window.__dropDash=false;window.__droppedDash=true;document.getElementById('match-settings').click();return;}}catch{}}return Reflect.apply(send,this,[data]);};` });
const [a, b] = await Promise.all(contexts.map(c => c.newPage()));
const observed = new Map<Page, Snapshot>();
for (const page of [a,b]) { page.on('pageerror', e => errors.push(e.message)); page.on('websocket', s => s.on('framereceived', ({payload}) => { if (typeof payload === 'string' && payload.startsWith('42[')) { try { const [event,p] = JSON.parse(payload.slice(2)); if(event === 'snapshot') observed.set(page,p.snapshot); } catch {} } })); }
async function lock(page: Page) { await page.bringToFront(); await until(async () => { if(await page.evaluate(() => document.pointerLockElement?.id === 'arena')) return true; const selector=await page.locator('#pause-menu').isVisible()?'#pause-resume':'#resume-button'; await page.locator(selector).click({timeout:500}).catch(()=>{}); return !!await page.evaluate(() => document.pointerLockElement?.id === 'arena'); }, 'pointer lock failed'); }
async function join(page: Page, name: string) { await page.locator('#callsign').fill(name); await page.locator('#join-open').click(); await page.locator('#room-code').fill(code); await page.locator('#join').click(); await page.locator('#lobby').waitFor({state:'visible'}); }
async function place(first: string, second: string, pillar=false) { await server.blobs.edit(code, data => { for(const p of data.room.players) Object.assign(p,{x:pillar?-7:0,z:p.id===first?(pillar?1:10):(pillar?-8:7),yaw:p.id===first?0:Math.PI,pitch:0,input:null,life:p.life+1}); }); await sleep(250); }
async function raw(page: Page, packet: object) { await page.evaluate(packet => (window as any).__gameSocket.send('42'+JSON.stringify(['input',packet])), packet); }
function input(id: string, extra: object = {}) { const p=player(id); return {seq:p.ack+1,life:p.life,mx:0,my:0,yaw:p.yaw,pitch:0,fire:false,dash:false,...extra}; }
async function kill(page: Page, shooter: string, victim: string) { await until(()=>player(shooter).hp>0 && server.now()>=player(shooter).protectUntil && player(victim).hp===100 && server.now()>=player(victim).protectUntil,'respawn/protection did not finish',7500); await place(shooter,victim); await lock(page); await page.mouse.down(); await until(()=>player(victim).hp===0,'three-hit elimination failed'); await page.mouse.up(); await sleep(120); }
async function start() { await b.bringToFront(); await b.locator('#start').click(); await Promise.all([a,b].map(p=>p.locator('#hud').waitFor({state:'visible'}))); await sleep(1100); }
try {
  await mkdir('artifacts/bug-sweep',{recursive:true});
  await Promise.all([a,b].map(p=>p.goto(server.url))); await Promise.all([a,b].map(p=>p.locator('#landing-connection').filter({hasText:'STATION ONLINE'}).waitFor()));
  await a.locator('#callsign').fill('SWEEPVEX'); await a.locator('#create').click({clickCount:2}); await a.locator('#lobby').waitFor({state:'visible'}); code=(await a.locator('#lobby-code').innerText()).trim();
  assert.ok(await a.locator('#start').isDisabled()); await join(b,'SWEEPNYX'); assert.equal(state().players.size,2); assert.equal(await b.locator('#start').isVisible(),false);
  idA=[...state().players.values()].find(p=>p.name==='SWEEPVEX')!.id; idB=[...state().players.values()].find(p=>p.name==='SWEEPNYX')!.id;
  pass('1–2: two independent muted browsers create/join distinct seats; solo Start is disabled and non-host Start is hidden');
  await b.reload(); await b.locator('#lobby').waitFor({state:'visible'}); assert.equal(state().players.size,2); assert.equal([...state().players.values()].find(p=>p.name==='SWEEPNYX')!.id,idB); pass('13: lobby refresh recovers the same seat without duplicates');
  await a.locator('#leave-lobby').click(); await a.locator('#confirm-accept').click(); await a.locator('#landing').waitFor({state:'visible'}); assert.equal(state().host,idB); await until(async()=>await b.locator('#start').isDisabled(),'single remaining host can start');
  await join(a,'SWEEPVEX'); idA=[...state().players.values()].find(p=>p.name==='SWEEPVEX')!.id; await until(async()=>!await b.locator('#start').isDisabled(),'new host Start stayed disabled'); pass('12: host leaves, remaining player becomes host; Start still requires the second player to rejoin');
  await start(); const endsAt=state().endsAt;
  await server.blobs.edit(code,d=>Object.assign(d.room.players.find(p=>p.id===idA)!,{x:10,z:10,yaw:0,input:null,life:player(idA).life+1})); await sleep(250); await lock(a);
  const beforeDash={x:player(idA).x,z:player(idA).z,dashAt:player(idA).dashAt}; await a.evaluate(()=>{(window as any).__dropDash=true;}); await a.keyboard.press('Shift'); await a.locator('#pause-menu').waitFor({state:'visible'}); await sleep(650);
  assert.deepEqual({x:player(idA).x,z:player(idA).z,dashAt:player(idA).dashAt},beforeDash); assert.ok(await a.evaluate(()=>(window as any).__droppedDash)); pass('FIX: a dropped dash followed immediately by Pause cannot retry into movement or a cooldown');
  const life=player(idA).life; await lock(b); await b.keyboard.down('KeyW'); const from={x:player(idB).x,z:player(idB).z}; await sleep(650); await b.keyboard.up('KeyW'); await b.mouse.click(640,400); await sleep(150); assert.ok(Math.hypot(player(idB).x-from.x,player(idB).z-from.z)>1); assert.equal(state().endsAt,endsAt);
  await lock(a); assert.equal(player(idA).life,life); assert.equal(player(idA).z,beforeDash.z); pass('8–9: Pause blocks only A; B moves and fires, deadline continues, Resume preserves A’s life and position');
  await server.blobs.edit(code,d=>Object.assign(d.room.players.find(p=>p.id===idA)!,{x:-7,z:-1,yaw:0,input:null,life:player(idA).life+1})); await sleep(250); await lock(a); await a.keyboard.down('KeyW'); await sleep(800); await a.keyboard.up('KeyW'); await sleep(120);
  assert.ok(player(idA).z>=-2.08 && validPosition(player(idA).x,player(idA).z)); await until(()=>Math.abs(observed.get(b)!.players.find(p=>p.id===idA)!.z-player(idA).z)<.15,'B disagrees on movement'); pass('3: walking stops at the pillar and the other client receives the same position');
  await place(idA,idB,true); await lock(a); await a.mouse.down(); await sleep(900); await a.mouse.up(); assert.equal(player(idB).hp,100); pass('4: pillar blocks real shots and damage');
  await place(idA,idB); const began=server.now(); await lock(a); await a.mouse.down(); await until(()=>player(idB).hp===66,'first shot failed'); await until(()=>player(idB).hp===0,'three hits did not eliminate'); await a.mouse.up(); assert.equal(player(idA).score,1); assert.ok(server.now()-began>=560);
  const respawnAt=player(idB).respawnAt, downPose={x:player(idB).x,z:player(idB).z}; await raw(b,input(idB,{my:1,fire:true,dash:true})); await sleep(200); assert.deepEqual({x:player(idB).x,z:player(idB).z},downPose); assert.equal(player(idA).hp,100);
  await until(()=>server.now()>=respawnAt-80,'clock stalled',5500); assert.equal(player(idB).hp,0); await until(()=>player(idB).hp===100,'respawn failed',1000); assert.ok(Math.abs(player(idB).protectUntil-respawnAt-1000)<40);
  await place(idA,idB); await lock(a); await a.mouse.down(); await raw(b,input(idB,{fire:true})); await sleep(450); await a.mouse.up(); assert.equal(player(idB).hp,100); assert.equal(player(idA).hp,100); await until(()=>server.now()>=player(idB).protectUntil,'protection did not expire',1500);
  pass('5: exposed shots deal 34; three hits score once; downed movement/fire are rejected; actual five-second respawn and one-second damage/fire protection');
  await server.blobs.edit(code,d=>Object.assign(d.room.players.find(p=>p.id===idA)!,{x:10,z:15,yaw:0,input:null,life:player(idA).life+1})); await sleep(250); const packet=input(idA,{seq:player(idA).ack+100,dash:true,x:9999,z:9999,damage:999,score:999}); await raw(a,packet); await sleep(80); const dashed=player(idA).z; assert.ok(Math.abs(dashed-9)<.05,`dash ended at ${dashed}; ack ${player(idA).ack}, sent ${packet.seq}`);
  for(let n=1;n<=12;n++) await raw(a,{...packet,seq:packet.seq+n}); await sleep(200); assert.ok(Math.abs(player(idA).z-dashed)<.05); assert.equal(player(idA).score,1);
  await place(idA,idB,true); const firePacket=input(idA,{seq:player(idA).ack+100,fire:true}); const shotStart=server.now(); for(let n=0;n<12;n++) await raw(a,{...firePacket,seq:firePacket.seq+n}); await sleep(90); const lastFire=player(idA).lastFire; assert.ok(lastFire-shotStart<100); await sleep(100); assert.equal(player(idA).lastFire,lastFire); assert.equal(player(idB).hp,100); pass('6: fire/dash spam respects cooldowns; client destinations, damage and score fields cannot grant authority');
  await until(()=>state().cell,'20-second cell spawn failed',24000); await server.blobs.edit(code,d=>{const p=d.room.players.find(p=>p.id===idA)!;Object.assign(p,{x:0,z:1.5,yaw:0,input:null,life:p.life+1});}); await sleep(250); await lock(a); await a.keyboard.down('KeyW'); await until(()=>player(idA).phaseUntil>server.now(),'cell unreachable'); await a.keyboard.up('KeyW'); const phaseUntil=player(idA).phaseUntil; assert.equal(state().cell,false);
  await server.blobs.edit(code,d=>{for(const p of d.room.players)Object.assign(p,{x:0,z:p.id===idA?0:3,yaw:p.id===idA?Math.PI:0,input:null,life:p.life+1});}); await sleep(250); await lock(b); await b.mouse.down(); await sleep(120); await b.mouse.up(); await until(()=>player(idA).hp===66,'phased operator cannot be hit'); await a.screenshot({path:'artifacts/bug-sweep/phase-match.png'}); await until(()=>player(idA).phaseUntil===0,'phase did not expire',5000); assert.ok(server.now()>=phaseUntil); pass('7: one reachable Phase Cell, real pickup, phased player remains hittable, effect expires after four seconds');
  for(let score=2;score<=10;score++) { await kill(a,idA,idB); assert.equal(player(idA).score,score); console.log(`ELIMINATIONS ${score}/10`); }
  assert.equal(state().phase,'ended'); assert.equal(state().winner,idA); await Promise.all([a,b].map(p=>p.locator('#results').waitFor({state:'visible'}))); for(const p of [a,b])assert.equal(await p.locator('#winner').innerText(),'SWEEPVEX'); matches.push({kind:'ten eliminations',elapsedMs:server.now()-state().startedAt,scores:[player(idA).score,player(idB).score],winner:'SWEEPVEX'}); pass('15a: ten genuine three-hit eliminations end immediately; both clients show the same winner');
  await b.bringToFront(); await b.locator('#replay').click(); await until(()=>state().phase==='lobby','replay failed'); await Promise.all([a,b].map(p=>p.locator('#lobby').waitFor({state:'visible'}))); assert.ok(state().connected().every(p=>p.hp===100&&p.score===0&&p.phaseUntil===0)); assert.equal(state().cell,false); await sleep(300); assert.equal(state().phase,'lobby'); pass('16: Play Again resets health, scores and Phase Cell without auto-start');
  await start(); await kill(a,idA,idB); await kill(b,idB,idA); const deadline=state().endsAt;
  assert.equal(player(idA).score,1); assert.equal(player(idB).score,1); assert.ok(player(idA).scoreAt<player(idB).scoreAt);
  while(state().phase==='playing'){ if(server.now()>deadline+2000)throw new Error('timeout stalled'); await sleep(1000); if(Math.floor(server.now()/1000)%30===0)console.log(`TIMEOUT ${Math.ceil((deadline-server.now())/1000)}s remaining`); }
  assert.ok(server.now()>=deadline); assert.equal(state().winner,idA); assert.equal(state().reason,'Contract time expired'); await Promise.all([a,b].map(p=>p.locator('#results').waitFor({state:'visible'}))); for(const p of [a,b])assert.equal(await p.locator('#winner').innerText(),'SWEEPVEX'); matches.push({kind:'unmodified 180-second timeout',elapsedMs:server.now()-state().startedAt,scores:[1,1],winner:'SWEEPVEX',tie:'earlier achievement'}); pass('15b: genuine 180-second timeout uses the earlier tied-score achievement; both clients agree');
  assert.deepEqual(errors,[]);
  await writeFile('artifacts/bug-sweep/combat-report.json',JSON.stringify({passed:true,date:new Date().toISOString(),checks,matches,errors,scope:'Two independent Chrome clients, built frontend and compiled production server. Server-only poses; no score/deadline edits or public cheat hooks. Muted desktop; touch and menu acceptance are separate reports. No physical devices or public deployment.'},null,2));
}catch(error){await writeFile('artifacts/bug-sweep/combat-report.json',JSON.stringify({passed:false,checks,matches,errors,failure:String(error)},null,2));throw error;}
finally{await browser.close();await server.close();}
