// Production-client acceptance test. Controlled poses are private to this test
// process; all movement, shooting, damage, dash, clocks, and pickups use sockets.
import{chromium,type Page}from'playwright';
import assert from'node:assert/strict';
import{mkdir,writeFile}from'node:fs/promises';
import{performance}from'node:perf_hooks';
import{createGameServer,serveProduction}from'./legacy/app';
import type{Room,Player}from'../server/game';
import type{GameEvent,Snapshot}from'../shared/protocol';
import{COLORS,validPosition}from'../shared/world';
const server=createGameServer();serveProduction(server.app);await new Promise<void>(r=>server.http.listen(0,'127.0.0.1',r));const address=server.http.address();assert.ok(address&&typeof address==='object');const url=`http://127.0.0.1:${address.port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=metal','--disable-background-timer-throttling','--disable-renderer-backgrounding']});
const checks:string[]=[],errors:string[]=[];const check=(s:string)=>{checks.push(s);console.log('PASS '+s);};const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));async function until(f:()=>boolean,label:string,ms=6000){const at=performance.now();while(!f()){if(performance.now()-at>ms)throw Error(label);await pause(20);}}
function observe(page:Page){const wire={state:null as Snapshot|null,shots:[]as GameEvent[],snapshots:0};page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/THREE|WebGL|shader/.test(m.text()))errors.push(m.text());});page.on('websocket',ws=>ws.on('framereceived',f=>{const raw=f.payload.toString();if(!raw.startsWith('42['))return;const e=JSON.parse(raw.slice(2));if(e[0]==='snapshot'){wire.state=e[1];wire.snapshots++;}if(e[0]==='event'&&e[1].type==='shot')wire.shots.push(e[1]);}));return wire;}
async function lock(p:Page){await p.bringToFront();if(await p.locator('#resume').isVisible())await p.locator('#resume-button').click();await p.waitForFunction(()=>document.pointerLockElement?.id==='arena');}
let room:Room,players:Player[]=[];
async function poses(specs:{p:Player;x:number;z:number;yaw?:number;pitch?:number}[]){for(const{p}of specs)Object.assign(p,{hp:0,input:null,respawnAt:performance.now()+60000});await pause(200);for(const{p,x,z,yaw=0,pitch=0}of specs){assert.ok(validPosition(x,z));Object.assign(p,{x,z,yaw,pitch,hp:100,protectUntil:0,respawnAt:0,input:null,life:p.life+1});}server.io.to(room.code).emit('snapshot',room.snapshot(performance.now()));await pause(240);}
const contexts=await Promise.all(Array.from({length:4},(_,i)=>browser.newContext({viewport:i?{width:720,height:480}:{width:1280,height:800}})));const pages=await Promise.all(contexts.map(c=>c.newPage()));const wires=pages.map(observe);const[a,b,c,d]=pages;
try{
 await mkdir('artifacts',{recursive:true});await a.addInitScript({content:'globalThis.__name=function(t){return t;};('+(()=>{const state={active:false,frames:[]as number[],last:0};(window as any).characterPerf=state;function frame(now:number){if(state.active&&state.last)state.frames.push(now-state.last);state.last=now;requestAnimationFrame(frame);}requestAnimationFrame(frame);}).toString()+')();'});
 await Promise.all(pages.map(p=>p.goto(url)));await a.locator('#landing-connection').filter({hasText:'STATION ONLINE'}).waitFor();await a.locator('#callsign').fill('ARMORVEX');await a.locator('#create').click();await a.locator('#lobby').waitFor({state:'visible'});const code=(await a.locator('#lobby-code').textContent())!;
 for(const[i,p]of pages.entries())if(i){await p.locator('#callsign').fill(['','ARMORNYX','ARMORION','ARMORHEX'][i]);await p.locator('#room-code').fill(code);await p.locator('#join').click();await p.locator('#lobby').waitFor({state:'visible'});}room=server.rooms.rooms.get(code)!;players=room.connected();assert.equal(players.length,4);assert.deepEqual(players.map(p=>p.color),COLORS);check('Four independent browser clients join one authoritative room with all four armor colors');
 await a.bringToFront();await a.locator('#start').click();await Promise.all(pages.map(p=>p.locator('#hud').waitFor({state:'visible'})));const[pa,pb,pc,pd]=players;
 await poses([{p:pa,x:-12,z:15},{p:pb,x:-12,z:11,yaw:Math.PI},{p:pc,x:-10,z:9,yaw:Math.PI},{p:pd,x:-14,z:9,yaw:Math.PI}]);await lock(a);await a.screenshot({path:'artifacts/character-live-colors.png'});
 for(const distance of [2.5,10,24]){await poses([{p:pa,x:-12,z:15},{p:pb,x:-12,z:15-distance,yaw:Math.PI/2}]);await a.screenshot({path:`artifacts/character-live-${distance}m.png`});}check('New operators are captured at 2.5, 10, and 24 meters inside the actual arena');
 await poses([{p:pa,x:-12,z:15},{p:pb,x:-12,z:7,yaw:0}]);await lock(b);await b.keyboard.down('s');await pause(500);await a.screenshot({path:'artifacts/character-live-run.png'});await b.keyboard.up('s');const before=pb.z;await until(()=>!!wires[0].state?.players.some(p=>p.id===pb.id&&Math.abs(p.z-7)>1),'remote movement missing');assert.ok(pb.z>8);
 await b.mouse.move(360,240);await b.mouse.move(650,190);await pause(200);assert.ok(Math.abs(pb.yaw)>.1);await a.screenshot({path:'artifacts/character-live-turn.png'});await b.keyboard.press('Shift');await pause(75);await a.screenshot({path:'artifacts/character-live-dash.png'});assert.ok(pb.dashAt>performance.now());assert.ok(validPosition(pb.x,pb.z));check('Remote running, aiming/turning, and a server-confirmed dash remain synchronized across clients');
 await lock(a);await poses([{p:pa,x:-12,z:12},{p:pb,x:-12,z:7,yaw:Math.PI}]);
 for(const hp of [66,32,0]){await a.mouse.down();await until(()=>pb.hp===hp,'expected 34-damage health step '+hp);await a.mouse.up();await pause(hp?70:150);await a.screenshot({path:hp?`artifacts/character-live-hit-${hp}.png`:'artifacts/character-live-elimination.png'});await pause(260);}
 assert.equal(pa.score,1);await pause(600);await a.screenshot({path:'artifacts/character-live-elimination-cleared.png'});await until(()=>pb.hp===100,'respawn did not occur',6500);assert.ok(pb.protectUntil>performance.now());await a.screenshot({path:'artifacts/character-live-respawn-protected.png'});await pause(1100);check('Three actual rifle hits eliminate; short remote collapse clears; five-second respawn and protection restore the operator');
 await until(()=>room.cell,'natural phase spawn failed',22000);await lock(b);await poses([{p:pa,x:0,z:3},{p:pb,x:-3,z:0,yaw:-Math.PI/2}]);await b.keyboard.down('w');await until(()=>pb.phaseUntil>performance.now(),'phase pickup failed');await b.keyboard.up('w');await until(()=>!!wires[0].state?.players.some(p=>p.id===pb.id&&p.phaseUntil>0),'remote phase state missing');await pause(220);await a.screenshot({path:'artifacts/character-live-phased.png'});await until(()=>pb.phaseUntil===0,'phase did not expire',5000);await until(()=>!!wires[0].state?.players.some(p=>p.id===pb.id&&p.phaseUntil===0),'remote phase expiration missing');await pause(220);await a.screenshot({path:'artifacts/character-live-phase-restored.png'});check('Phase translucency and protection remain visible; Phase Cell expiration restores suit materials');
 await lock(a);await poses([{p:pa,x:0,z:2},{p:pb,x:0,z:-8}]);await a.mouse.down();await pause(700);await a.mouse.up();assert.equal(pb.hp,100);check('Detailed armor preserves server cover blocking and stable hit detection');
 await poses([{p:pa,x:-12,z:15},{p:pb,x:-12,z:10,yaw:Math.PI},{p:pc,x:-10,z:8,yaw:Math.PI},{p:pd,x:-14,z:8,yaw:Math.PI}]);await lock(a);await a.evaluate(()=>(window as any).characterPerf.active=true);
 const start=performance.now();for(let i=0;i<8;i++){const page=pages[1+i%3];await lock(page);await page.keyboard.down(i%2?'a':'d');await pause(900);await page.keyboard.up(i%2?'a':'d');await page.mouse.down();await pause(450);await page.mouse.up();await pause(2200);assert.equal(room.connected().length,4);assert.equal(room.phase,'playing');if(i%2===1)console.log('FOUR-CLIENT COMBAT '+Math.round((performance.now()-start)/1000)+'s');}
 const metrics=await a.evaluate(()=>{const data=(window as any).characterPerf;data.active=false;const f=(data.frames as number[]).sort((a,b)=>a-b),gl=(document.querySelector('#arena')as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return{frames:f.length,medianMs:f[Math.floor(f.length*.5)],p95Ms:f[Math.floor(f.length*.95)],renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER)};});assert.ok(metrics.frames>500);assert.ok(wires.every(w=>w.snapshots>200));check('Four active clients sustain movement and firing while primary-client frame timing is measured');
 await contexts[3].close();await contexts[2].close();await contexts[1].close();await a.locator('#results').waitFor({state:'visible'});assert.equal(room.winner,pa.id);await a.locator('#replay').click();await a.locator('#lobby').waitFor({state:'visible'});assert.equal(pa.score,0);check('Disconnect victory and replay still return the remaining player to a clean lobby');assert.deepEqual(errors,[]);
 await writeFile('artifacts/character-live-report.json',JSON.stringify({date:new Date().toISOString(),checks,errors,metrics,colors:COLORS,network:wires.map(w=>({snapshots:w.snapshots,shots:w.shots.length})),limits:['Four automated Chrome contexts on one Mac; no human anatomical/readability study or physical-phone performance test.','Controlled server starting poses only; real DOM input and sockets; gameplay rules/hit volumes unchanged.','Visual contact and material inspection do not prove no clipping at every extreme camera/aim angle.']},null,2));console.log(JSON.stringify({checks:checks.length,metrics}));
}catch(e){console.error(e);process.exitCode=1;for(const[i,p]of pages.entries())if(!p.isClosed())await p.screenshot({path:`artifacts/failure-character-live-${i}.png`}).catch(()=>{});}finally{await browser.close();await server.close();}
