import {chromium,type Page} from 'playwright';
import {build} from 'esbuild';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {performance} from 'node:perf_hooks';
import {createGameServer,serveProduction} from './legacy/app';
import type {Room,Player} from '../server/game';
import type {Snapshot} from '../shared/protocol';
const bundle=await build({entryPoints:['tests/music-harness.ts'],bundle:true,write:false,format:'iife',platform:'browser'});
const server=createGameServer();server.app.get('/__musicqa',(_q,r)=>r.type('html').send('<!doctype html><button>Enable audio</button><script src="/__musicqa.js"></script>'));server.app.get('/__musicqa.js',(_q,r)=>r.type('application/javascript').send(bundle.outputFiles[0].text));serveProduction(server.app);
await new Promise<void>(r=>server.http.listen(0,'127.0.0.1',r));const address=server.http.address();assert.ok(address&&typeof address==='object');const url=`http://127.0.0.1:${address.port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-webgl','--use-angle=metal','--disable-background-timer-throttling','--disable-renderer-backgrounding']});
const checks:string[]=[],errors:string[]=[],matches:any[]=[];const check=(s:string)=>{checks.push(s);console.log('PASS '+s);};
const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));async function until(fn:()=>boolean,label:string,limit=6000){const start=performance.now();while(!fn()){if(performance.now()-start>limit)throw Error(label);await pause(25);}}
function observe(p:Page){const wire={state:null as Snapshot|null,shots:0};p.on('pageerror',e=>errors.push(e.message));p.on('websocket',ws=>ws.on('framereceived',f=>{const raw=f.payload.toString();if(!raw.startsWith('42['))return;const e=JSON.parse(raw.slice(2));if(e[0]==='snapshot')wire.state=e[1];if(e[0]==='event'&&e[1].type==='shot')wire.shots++;}));return wire;}
async function audit(p:Page){await p.addInitScript({content:'globalThis.__name=function(t){return t;};('+(()=>{
 const start=AudioBufferSourceNode.prototype.start,connect=AudioNode.prototype.connect;
 const list:{duration:number;loop:boolean;at:number;offset:number;ended:boolean}[]=[],analysers:AnalyserNode[]=[];let peak=0,recent:number[]=[];
 (AudioNode.prototype as any).connect=function(...args:any[]){if(args[0]instanceof AudioDestinationNode&&!(this instanceof AnalyserNode)){const a=this.context.createAnalyser();a.fftSize=2048;analysers.push(a);Reflect.apply(connect,this,[a]);Reflect.apply(connect,a,args);return args[0];}return Reflect.apply(connect,this,args);};
 AudioBufferSourceNode.prototype.start=function(...args){if(this.buffer){const entry={duration:this.buffer.duration,loop:this.loop,at:this.context.currentTime,offset:args[1]??0,ended:false};list.push(entry);this.addEventListener('ended',()=>entry.ended=true,{once:true});}return Reflect.apply(start,this,args);};
 const pcm=new Float32Array(2048);setInterval(()=>{let max=0;for(const a of analysers){a.getFloatTimeDomainData(pcm);for(const x of pcm)max=Math.max(max,Math.abs(x));}peak=Math.max(peak,max);recent.push(max);if(recent.length>10)recent.shift();},50);
 Object.assign(window,{scoreAudit:{read:()=>({sources:list,peak,recentPeak:Math.max(0,...recent),contexts:analysers.length}),reset:()=>{list.length=0;peak=0;recent=[];}}});
 }).toString()+')();'});}
const read=(p:Page)=>p.evaluate(()=>(window as any).scoreAudit.read());
const change=async(p:Page,id:string,value:number)=>p.locator(id).evaluate((e,v)=>{(e as HTMLInputElement).value=String(v);e.dispatchEvent(new Event('input',{bubbles:true}));},value);
async function lock(p:Page){await p.bringToFront();if(await p.locator('#resume').isVisible())await p.locator('#resume-button').click();await p.waitForFunction(()=>document.pointerLockElement?.id==='arena');}
let room:Room,pa:Player,pb:Player;
async function pose(placements:{p:Player;x:number;z:number;yaw?:number}[]){placements.forEach(({p})=>Object.assign(p,{hp:0,respawnAt:performance.now()+60000,input:null}));await pause(180);placements.forEach(({p,x,z,yaw=0})=>Object.assign(p,{x,z,yaw,pitch:0,hp:100,protectUntil:0,respawnAt:0,input:null,life:p.life+1}));server.io.to(room.code).emit('snapshot',room.snapshot(performance.now()));await pause(220);}
let labResult:any;
try{
 await mkdir('artifacts',{recursive:true});const lab=await browser.newPage();observe(lab);await lab.goto(url+'/__musicqa');await lab.locator('button').click();await lab.waitForFunction(()=>(window as any).musicQA.sound.status==='ready');await lab.evaluate(()=>(window as any).musicQA.ready());
 labResult=await lab.evaluate(()=>(window as any).musicQA.lab());await writeFile('artifacts/music-mix-review.wav',Buffer.from(labResult.wav,'base64'));delete labResult.wav;
 assert.equal(Object.keys(labResult.assets).length,8);for(const a of Object.values(labResult.assets)as any[]){assert.equal(a.channels,2);assert.equal(a.rate,32000);assert.ok(a.monoEnergyRatio>.97);assert.ok(a.boundary<.006);}check('All eight compressed cues decode at exact lengths; loop edges are bounded and mono retains over 97% of stereo energy');
 assert.ok(labResult.score.rms<labResult.shot.rms*.4);assert.ok(labResult.score.rms<labResult.foot.rms*.7);assert.ok(labResult.ducked.rms<labResult.score.rms*.5);assert.ok(labResult.combined.peak<.88);assert.deepEqual(labResult.silence,[0,0,0]);check('Default score sits below rifle/footstep windows; ducking reduces measured energy; Music zero, Master zero, and Mute render silence');
 let report=await lab.evaluate(()=>(window as any).musicQA.step('playing',0));await pause(300);report=await lab.evaluate(()=>(window as any).musicQA.report());assert.equal(report.metrics.starts.start,1);
 await lab.evaluate(()=>(window as any).musicQA.step('playing',15));await pause(300);report=await lab.evaluate(()=>(window as any).musicQA.shot(30));assert.equal(report.metrics.ducks,0);
 await lab.evaluate(()=>(window as any).musicQA.shot(4));await pause(75);report=await lab.evaluate(()=>(window as any).musicQA.report());assert.ok(report.state.duck<.4);assert.equal(report.state.targets.intensity,.8);
 await pause(6800);report=await lab.evaluate(()=>(window as any).musicQA.report());assert.ok(report.state.duck>.98);assert.equal(report.state.targets.intensity,0);assert.equal(report.metrics.starts.combat,1);assert.equal(report.metrics.starts.intensity,1);check('Nearby fire engages intensity and ducks; distant fire does neither; calm fades the same running stem without restarting');
 await lab.evaluate(()=>(window as any).musicQA.pickup());await pause(120);report=await lab.evaluate(()=>(window as any).musicQA.report());assert.equal(report.metrics.starts.shimmer,1);
 await lab.evaluate(()=>{const q=(window as any).musicQA;q.event({type:'kill',killer:'A',victim:'B'});q.step('playing',120);for(let i=0;i<10;i++)q.step('playing',121+i*.05);});report=await lab.evaluate(()=>(window as any).musicQA.report());assert.equal(report.metrics.finalEntries,1);assert.equal(report.metrics.starts.final,1);check('Phase pickup adds one small shimmer; kills add no music sting; final-minute variation enters exactly once');
 await lab.evaluate(()=>(window as any).musicQA.step('ended',180,'A'));await pause(350);report=await lab.evaluate(()=>(window as any).musicQA.report());assert.deepEqual(report.state.active,['victory']);assert.equal(report.state.voices,1);
 await lab.evaluate(()=>(window as any).musicQA.step('lobby'));await pause(1800);report=await lab.evaluate(()=>(window as any).musicQA.report());assert.deepEqual(report.state.active,['lobby']);assert.equal(report.state.voices,1);
 await lab.evaluate(()=>{const q=(window as any).musicQA;q.next();q.step('playing',20);q.step('ended',180,'B');});await pause(350);report=await lab.evaluate(()=>(window as any).musicQA.report());assert.deepEqual(report.state.active,['defeat']);
 await pause(5100);report=await lab.evaluate(()=>(window as any).musicQA.report());assert.deepEqual(report.state.active,[]);assert.equal(report.metrics.starts.defeat,1);check('Victory and defeat replace combat with no surviving combat sources; ending stops once; replay crossfades to lobby in 1.6 seconds');
 await lab.evaluate(()=>{const q=(window as any).musicQA;q.next();q.step('playing',15);q.pause(true);q.step('playing',145);});report=await lab.evaluate(()=>(window as any).musicQA.report());assert.deepEqual(report.state.active,[]);await lab.evaluate(()=>(window as any).musicQA.pause(false));report=await lab.evaluate(()=>(window as any).musicQA.report());assert.ok(report.state.active.includes('final'));assert.equal(report.metrics.starts.start,1);
 await lab.evaluate(()=>(window as any).musicQA.disconnect());await pause(250);report=await lab.evaluate(()=>(window as any).musicQA.report());assert.equal(report.state.voices,0);check('Suspension/resume follows current match position without replaying intro; disconnect clears every score source');await lab.close();
 if(!process.argv.includes('--lab')){
 const ca=await browser.newContext({viewport:{width:1280,height:800}}),cb=await browser.newContext({viewport:{width:960,height:640}}),a=await ca.newPage(),b=await cb.newPage();const wa=observe(a),wb=observe(b);await audit(a);await audit(b);await Promise.all([a.goto(url),b.goto(url)]);
 await a.locator('#landing-connection').filter({hasText:'STATION ONLINE'}).waitFor();assert.equal((await read(a)).contexts,0);await a.locator('#settings-open').click();await change(a,'#audio-music',31);await a.reload();await a.locator('#settings-open').click();assert.equal(await a.locator('#audio-music').inputValue(),'31');await change(a,'#audio-music',40);await a.screenshot({path:'artifacts/music-settings-desktop.png'});await a.locator('#settings button').filter({hasText:'SAVE & CLOSE'}).click();
 await a.waitForFunction(()=>(window as any).scoreAudit.read().sources.some((s:any)=>s.duration===60));check('Production autoplay stays locked until interaction; Music slider persists independently and lobby playback starts');
 await a.locator('#callsign').fill('SCOREVEX');await a.locator('#create').click();await a.locator('#lobby').waitFor({state:'visible'});const code=(await a.locator('#lobby-code').textContent())!;
 await b.locator('#callsign').fill('SCORENYX');await b.locator('#room-code').fill(code);await b.locator('#join').click();await b.locator('#lobby').waitFor({state:'visible'});room=server.rooms.rooms.get(code)!;[pa,pb]=room.connected();await pause(1800);
 for(const muted of [false,true]){
  if(muted)for(const p of [a,b]){await p.locator('#settings-open').click();await change(p,'#audio-music',0);await p.locator('#settings button').filter({hasText:'SAVE & CLOSE'}).click();}await pause(200);
  await a.evaluate(()=>(window as any).scoreAudit.reset());await b.evaluate(()=>(window as any).scoreAudit.reset());const shotBefore=wa.shots;
  await a.bringToFront();await a.locator('#start').click();await Promise.all([a.locator('#hud').waitFor({state:'visible'}),b.locator('#hud').waitFor({state:'visible'})]);const deadline=room.endsAt;assert.ok(Math.abs(deadline-room.startedAt-180000)<.001,'Server match length must be 180 seconds');
  for(const [p,player,remote]of [[a,pa,wb],[b,pb,wa]]as const){await lock(p);const z=player.z;await p.keyboard.down('w');await pause(650);await p.keyboard.up('w');await until(()=>!!remote.state?.players.some(q=>q.id===player.id&&Math.abs(q.z-z)>1),'remote move missing');}
  await lock(a);await pose([{p:pa,x:-12,z:10},{p:pb,x:-12,z:5}]);await a.mouse.down();await until(()=>pb.hp===0,'three hits failed');await a.mouse.up();await until(()=>pb.hp===100,'respawn failed',6500);await pause(1100);
  await lock(b);await pose([{p:pb,x:12,z:10},{p:pa,x:12,z:5}]);await b.mouse.down();await until(()=>pa.hp===0,'return fire failed');await b.mouse.up();await until(()=>pa.hp===100,'host respawn failed',6500);await pause(1100);
  await until(()=>room.cell,'phase spawn failed',22000);await lock(a);await pose([{p:pa,x:-4,z:0,yaw:-Math.PI/2},{p:pb,x:12,z:10}]);await a.keyboard.down('w');await until(()=>pa.phaseUntil>performance.now(),'phase pickup failed');await a.keyboard.up('w');await until(()=>pa.phaseUntil===0,'phase expiry failed',5000);
  let cycle=0;while(performance.now()<deadline-5000){const p=cycle%2?a:b,player=cycle%2?pa:pb;await lock(p);await pose([{p:player,x:cycle%2?-12:12,z:16}]);await p.keyboard.down('w');await pause(700);await p.keyboard.up('w');await p.mouse.down();await pause(600);await p.mouse.up();await pause(3500);assert.equal(room.connected().length,2);assert.equal(room.phase,'playing');cycle++;if(cycle%4===0)console.log(`MUSIC ${muted?'MUTED':'ON'} ${Math.round((performance.now()-room.startedAt)/1000)} / 180 seconds`);}
  await until(()=>room.phase==='ended','natural timeout failed',8000);await Promise.all([a.locator('#results').waitFor({state:'visible'}),b.locator('#results').waitFor({state:'visible'})]);await pause(350);
  const ra=await read(a),rb=await read(b),scoreSources=(r:any)=>r.sources.filter((s:any)=>[60,30,7.5,5,2.25].includes(s.duration));
  if(muted){assert.equal(scoreSources(ra).length,0);assert.equal(scoreSources(rb).length,0);}else{for(const r of [ra,rb]){const stems=r.sources.filter((s:any)=>s.duration===30);assert.equal(stems.length,3);const intro=r.sources.find((s:any)=>s.duration===7.5);assert.ok(stems[2].at-intro.at>=119.5&&stems[2].at-intro.at<=121);assert.ok(scoreSources(r).every((s:any)=>s.duration!==30||s.ended));assert.ok(r.sources.some((s:any)=>s.duration===7.5&&!s.loop));}assert.ok(ra.sources.some((s:any)=>s.duration===2.25));assert.ok([ra,rb].some(r=>r.sources.some((s:any)=>s.duration===5)));}
  for(const r of [ra,rb]){assert.ok(r.peak>.01&&r.peak<.9);assert.ok(r.sources.filter((s:any)=>Math.abs(s.duration-.27)<.001).length>30);assert.ok(r.sources.some((s:any)=>Math.abs(s.duration-.18)<.001));}
  const winner=room.players.get(room.winner!)!.name;assert.equal(await a.locator('#winner').textContent(),winner);assert.equal(await b.locator('#winner').textContent(),winner);assert.equal(room.endsAt,deadline);assert.ok(performance.now()>=deadline);
  matches.push({music:muted?'muted':'on',durationMs:deadline-room.startedAt,shots:wa.shots-shotBefore,scores:[pa.score,pb.score],winner,a:{peak:ra.peak,scoreSources:scoreSources(ra)},b:{peak:rb.peak,scoreSources:scoreSources(rb)}});check(`Natural 180-second two-client match with music ${muted?'muted':'on'}: both move/fire, eliminate/respawn, collect Phase Cell, reach final minute and agree on winner`);
  await a.locator('#replay').click();await Promise.all([a.locator('#lobby').waitFor({state:'visible'}),b.locator('#lobby').waitFor({state:'visible'})]);assert.equal(pa.score,0);assert.equal(pb.score,0);await pause(1800);
 }
 await ca.close();await cb.close();
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});observe(mobile);await mobile.goto(url);await mobile.locator('#settings-open').tap();await change(mobile,'#audio-music',0);await mobile.locator('#audio-music').scrollIntoViewIfNeeded();await mobile.screenshot({path:'artifacts/music-settings-mobile.png'});assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await mobile.locator('#audio-music').inputValue(),'0');await mobile.close();check('Music control is accessible by touch in portrait settings without horizontal overflow');
 const fail=await browser.newPage();observe(fail);await audit(fail);await fail.route('**/music/*.flac*',r=>r.abort());await fail.goto(url);await fail.locator('#callsign').fill('NOFILES');await fail.locator('#solo').click();await fail.locator('#lobby').waitFor({state:'visible'});await fail.locator('#start').click();await fail.locator('#hud').waitFor({state:'visible'});await lock(fail);await pause(1500);await fail.mouse.down();await pause(1000);await fail.mouse.up();const failed=await read(fail);assert.ok(failed.sources.some((s:any)=>Math.abs(s.duration-.27)<.001));assert.ok(failed.peak>.01);await fail.close();check('All music files failing to load still permits a real solo match and audible authoritative gunfire');
 }
 assert.deepEqual(errors,[]);await writeFile('artifacts/music-report.json',JSON.stringify({date:new Date().toISOString(),passed:true,checks,errors,lab:labResult,matches,listenedByEar:false,physicalDevices:false,fixtureDisclosure:'Two automated Chrome contexts on one Mac; controlled poses only. Real DOM input, sockets, server scoring and two unmodified 180-second clocks. No human listening or WAN deployment claimed.'},null,2));console.log(`All ${checks.length} score checks passed.`);
}catch(e){console.error(e);await writeFile('artifacts/music-report.json',JSON.stringify({passed:false,checks,errors,lab:labResult,matches,failure:String(e)},null,2));process.exitCode=1;}finally{await browser.close();await server.close();}
